### PR TITLE
Update symmetry property and add compute_symmetry_reduced_orientations as alternative to set_symmetry

### PR DESCRIPTION
**Pull request by harripj**
From the discussion in #235 and #233, I wanted to update the use of the symmetry property, with the possibility to add a to-be-decided renamed ```set_symmetry``` function, which will perform the same operation. ```set_symmetry``` is left untouched to keep the tests passing, but now the work is performed in the to-be-decided renamed ```set_symmetry``` function which requires no symmetry arguments. The tests have been updated to call the new function to return the same values as previously calculated with ```set_symmetry```.

### CODE REVIEW

**Comment by hakonanes** [comment]
Thanks! Looks like we agree on the approach here. However, I suggest pointing this directly to orix, including the symmetry setter and getter from #235 in orix, and then we can use that in the IPF PR?

**Comment by hakonanes** [comment]
I'm sorry I didn't propose this right away.

**Comment by harripj** [comment]
No problem! I think the easiest way will be that I create a new PR just for this in orix.

**Comment by hakonanes** [comment]
Agree, this is such a fundamental change to how the everyday of (mis)orientations in orix, so we should treat it separately from the IPF functionality (although that work highlights the need for this change).

**Pull request closed without merging**
